{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: flask in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: Werkzeug>=0.15 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from flask) (0.16.1)\n",
      "Requirement already satisfied: Jinja2>=2.10.1 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from flask) (2.11.1)\n",
      "Requirement already satisfied: itsdangerous>=0.24 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from flask) (1.1.0)\n",
      "Requirement already satisfied: click>=5.1 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from flask) (7.1.1)\n",
      "Requirement already satisfied: MarkupSafe>=0.23 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from Jinja2>=2.10.1->flask) (1.1.1)\n",
      "Requirement already satisfied: flask_restful in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (0.3.8)\n",
      "Requirement already satisfied: six>=1.3.0 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from flask_restful) (1.14.0)\n",
      "Requirement already satisfied: aniso8601>=0.82 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from flask_restful) (8.0.0)\n",
      "Requirement already satisfied: Flask>=0.8 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from flask_restful) (1.1.2)\n",
      "Requirement already satisfied: pytz in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from flask_restful) (2019.3)\n",
      "Requirement already satisfied: itsdangerous>=0.24 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from Flask>=0.8->flask_restful) (1.1.0)\n",
      "Requirement already satisfied: Jinja2>=2.10.1 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from Flask>=0.8->flask_restful) (2.11.1)\n",
      "Requirement already satisfied: Werkzeug>=0.15 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from Flask>=0.8->flask_restful) (0.16.1)\n",
      "Requirement already satisfied: click>=5.1 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from Flask>=0.8->flask_restful) (7.1.1)\n",
      "Requirement already satisfied: MarkupSafe>=0.23 in c:\\users\\mridu\\anaconda3\\envs\\tf\\lib\\site-packages (from Jinja2>=2.10.1->Flask>=0.8->flask_restful) (1.1.1)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Mridu\\Anaconda3\\envs\\tf\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\n",
      "C:\\Users\\Mridu\\Anaconda3\\envs\\tf\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\n",
      "C:\\Users\\Mridu\\Anaconda3\\envs\\tf\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\n",
      "C:\\Users\\Mridu\\Anaconda3\\envs\\tf\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\n",
      "C:\\Users\\Mridu\\Anaconda3\\envs\\tf\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\n",
      "C:\\Users\\Mridu\\Anaconda3\\envs\\tf\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\n",
      "C:\\Users\\Mridu\\Anaconda3\\envs\\tf\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\n",
      "C:\\Users\\Mridu\\Anaconda3\\envs\\tf\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\n",
      "C:\\Users\\Mridu\\Anaconda3\\envs\\tf\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\n",
      "C:\\Users\\Mridu\\Anaconda3\\envs\\tf\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\n",
      "C:\\Users\\Mridu\\Anaconda3\\envs\\tf\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\n",
      "C:\\Users\\Mridu\\Anaconda3\\envs\\tf\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\n"
     ]
    }
   ],
   "source": [
    "!pip install flask\n",
    "!pip install flask_restful\n",
    "\n",
    "from flask import Flask,request\n",
    "from flask_restful import Resource,Api\n",
    "import tensorflow as tf\n",
    "import cv2\n",
    "import cv2\n",
    "import matplotlib.pyplot as plt\n",
    "import os\n",
    "import io\n",
    "import base64\n",
    "\n",
    "app=Flask(__name__)\n",
    "api=Api(app)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "class pre_process():\n",
    "    \n",
    "    def pipeline(self,image):\n",
    "        \n",
    "\n",
    "        \n",
    "        img=cv2.imread(image)\n",
    "        img=self.check_size(img)\n",
    "        img=self.check_channels(img)\n",
    "        img=self.convert_array(img)\n",
    "        img=self.expand_dims(img)\n",
    "        img=self.caster(img)\n",
    "        #print(len(glob.glob(os.path.join(datadir,\"*\",\"*\" ,\"*.png\"))))\n",
    "        \n",
    "        return img\n",
    "\n",
    "     \n",
    "    def check_channels(self,img):\n",
    "        \n",
    "        if img.shape[-1]==3:\n",
    "            img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)\n",
    "            return img\n",
    "        elif img.shape[-1]==1:\n",
    "            img=cv2.cvtColor(img,cv2.COLOR_GRAY2RGB)\n",
    "            return img\n",
    "        else:\n",
    "            raise ValueError(\"{} channel is not supported\".format(img.shape[-1]))\n",
    "            \n",
    "            \n",
    "    def check_size(self,img):\n",
    "        \n",
    "        if img.shape[0:2]==(300,300):\n",
    "            return img\n",
    "\n",
    "        else:\n",
    "            img=cv2.resize(img,(300,300),interpolation=cv2.INTER_NEAREST)\n",
    "            return img\n",
    "    \n",
    "    def check_format(self,img):\n",
    "        \n",
    "        chck=(os.path.splitext(os.path.basename(img))[1])\n",
    "        if chck == '.png'or chck=='.jpg':\n",
    "            pass\n",
    "        else:\n",
    "            raise ValueError(\"{} is not supported\".format(chck))\n",
    "    def convert_array(self,img):\n",
    "        img=np.asarray(img)\n",
    "        return img\n",
    "\n",
    "    def expand_dims(sef,img):\n",
    "        if img.ndim==3:\n",
    "            img=np.expand_dims(img,axis=0)\n",
    "            return img\n",
    "        else:\n",
    "            raise ValueError(\"Input dim {} does not match expected dim {}\".format(img.ndim,3))\n",
    "\n",
    "    def caster(self,img):\n",
    "        img=tf.cast(img,tf.int64)\n",
    "        return img\n",
    "    \n",
    "\n",
    "class predictions(Resource, pre_process):\n",
    "    \n",
    "    def __init__(self):\n",
    "        \n",
    "        self.model=tf.keras.load_model('C:/Users\\Mridu\\Flask\\final_model_train1.hdf5')\n",
    "        \n",
    "        \n",
    "    def pipeline(self, data):\n",
    "        \n",
    "        out_im=pre_process.pipeline(self,data)\n",
    "        return out_im\n",
    "    \n",
    "    def pred(self,image):\n",
    "        \n",
    "        img=self.pipeline(image)\n",
    "        predict_score=self.model.predict(img)\n",
    "        return (predict_score.tolist())\n",
    "    \n",
    "    def get(self,img_path):\n",
    "        \n",
    "        try:\n",
    "            self.img_path =request.form['data']\n",
    "        except Exception:\n",
    "            return jsonify(status_code='400', msg='Bad Request'), 400\n",
    "        \n",
    "        img_path = base64.b64decode(data)\n",
    "\n",
    "        img = io.BytesIO(img_path)\n",
    "        precition=self.pred(img)\n",
    "        predict_class='a' if float(''.join(map(str,prediction[0])))>0 else 'b'\n",
    "        \n",
    "        return jsonify({\"output\": predict_class})\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "api.add_resource(predictions,'/<string:text>')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "if __name__==\"__main__\":\n",
    "    app.run(host='0.0.0.0',port='8080')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
